// <auto-generated />
using System;
using Lilia.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(LiliaDBContext))]
    [Migration("20260801145225_AddRegistryAndShops")]
    partial class AddRegistryAndShops
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Lilia.Domain.Entities.BaseUnit", b =>
                {
                    b.Property<Guid>("InternalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganisationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistryNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegistryUnitID")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("InternalID");

                    b.HasIndex("OrganisationID");

                    b.HasIndex("RegistryUnitID");

                    b.ToTable("Units");

                    b.HasDiscriminator<string>("UnitType").HasValue("BaseUnit");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Lilia.Domain.Entities.Organisation", b =>
                {
                    b.Property<Guid>("InternalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentOrganisationID")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("PlayerDiscordID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InternalID");

                    b.HasIndex("ParentOrganisationID");

                    b.HasIndex("PlayerDiscordID", "ShortCode")
                        .IsUnique();

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Lilia.Domain.Entities.Player", b =>
                {
                    b.Property<ulong>("DiscordID")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscordID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Lilia.Domain.Entities.RegistryUnit", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasStats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Modslots")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("RegistryUnits");
                });

            modelBuilder.Entity("Lilia.Domain.Entities.Shop", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Lilia.Domain.Entities.ShopRegistryUnit", b =>
                {
                    b.Property<Guid>("ShopID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegistryUnitID")
                        .HasColumnType("TEXT");

                    b.HasKey("ShopID", "RegistryUnitID");

                    b.HasIndex("RegistryUnitID");

                    b.ToTable("ShopRegistryUnits");
                });

            modelBuilder.Entity("Lilia.Domain.Entities.Units.Starfighter", b =>
                {
                    b.HasBaseType("Lilia.Domain.Entities.BaseUnit");

                    b.HasDiscriminator().HasValue("Starfighter");
                });

            modelBuilder.Entity("Lilia.Domain.Entities.BaseUnit", b =>
                {
                    b.HasOne("Lilia.Domain.Entities.Organisation", "Organisation")
                        .WithMany("AssignedUnits")
                        .HasForeignKey("OrganisationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lilia.Domain.Entities.RegistryUnit", "Blueprint")
                        .WithMany()
                        .HasForeignKey("RegistryUnitID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blueprint");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Lilia.Domain.Entities.Organisation", b =>
                {
                    b.HasOne("Lilia.Domain.Entities.Organisation", "ParentOrganisation")
                        .WithMany("SubOrganisations")
                        .HasForeignKey("ParentOrganisationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lilia.Domain.Entities.Player", "Player")
                        .WithMany("Organisations")
                        .HasForeignKey("PlayerDiscordID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentOrganisation");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Lilia.Domain.Entities.Player", b =>
                {
                    b.OwnsOne("Lilia.Domain.Entities.UnitCount", "UnitCount", b1 =>
                        {
                            b1.Property<ulong>("PlayerDiscordID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Units")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PlayerDiscordID");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDiscordID");
                        });

                    b.Navigation("UnitCount")
                        .IsRequired();
                });

            modelBuilder.Entity("Lilia.Domain.Entities.ShopRegistryUnit", b =>
                {
                    b.HasOne("Lilia.Domain.Entities.RegistryUnit", "RegistryUnit")
                        .WithMany()
                        .HasForeignKey("RegistryUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lilia.Domain.Entities.Shop", "Shop")
                        .WithMany("AvailableUnits")
                        .HasForeignKey("ShopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistryUnit");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Lilia.Domain.Entities.Organisation", b =>
                {
                    b.Navigation("AssignedUnits");

                    b.Navigation("SubOrganisations");
                });

            modelBuilder.Entity("Lilia.Domain.Entities.Player", b =>
                {
                    b.Navigation("Organisations");
                });

            modelBuilder.Entity("Lilia.Domain.Entities.Shop", b =>
                {
                    b.Navigation("AvailableUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
